### ISSUE TITLE
Création d'une CI pour 10

### ISSUE THREAD

**Issue by quentinmdl** [juu-aix-ynov-campus/documentation#1]
# Prérequis pour la création d'une CI via GitHub Actions

## FRONT
   - Tehnologie : react-native,expo, typescript
   - Actions souhaitées :
       - **dep**: _npm i_ 
       - **build** : _npm run build_
       - **test** : _npm run test_

## BACK
   - Tehnologie : nodeJs, fastify, prisma, swagger, typescript
   - Actions souhaitées :
       - **dep** : _npm i_ 
       - **build** : _npm run build_
       - **test** : _npm run test_
       - **migrate** : _npm run migrate_

**Comment by j-catania** [comment]
@quentinmdl,
Quand seriez-vous dispo pour créer vos CI Back et Front ?

**Comment by quentinmdl** [comment]
Bonjour, rien n'est finalisé et fonctionnel pour l'instant, et encore moins pour automatiser quoi que ce soit en environnement de production. Nous sommes encore dans la phase de réflexion et d'initialisation des 2 stacks. On peut se rendre disponible en fin de journée vers 17h pour en discuter si cela est vraiment urgent.
