### ISSUE TITLE
Création d'une CI pour 7

### ISSUE THREAD

**Issue by achrafameur** [juu-aix-ynov-campus/documentation#2]
## FRONT
   - Tehnologie : _ReactJS_
   - Actions souhaitées : 
       - **Dépendances** : _npm i_
       - **build** : _npm run build_
       - **test** : _npm run test_

## BACK
   - Tehnologie : _(NestJS,swagger)_
   - Actions souhaitées : 
       - **Dépendances** : _npm i_
       - **build** : _npm run build_
       - **test** : _npm run test_

**Comment by j-catania** [comment]
@achrafameur, 
Seriez-vous disponible cet après-midi pour mettre en place les CI sur votre Front et Back ?

**Comment by achrafameur** [comment]
d'accord Monsieur, on se fait une réunion avec toute l'équipe vers 15h
15h30 si ca vous va ?

Le jeu. 23 mars 2023 à 11:38, Julien Catania ***@***.***> a
écrit :

**Comment by j-catania** [comment]
Front React avec CI et déployé sur une GHPages
Back Nest.JS avec CI
