### ISSUE TITLE
Création d'une CI pour 9

### ISSUE THREAD

**Issue by philippe-lek** [juu-aix-ynov-campus/documentation#3]
## FRONT
   - Tehnologie : React
   - Actions souhaitées :
       - **dependencies** : npm i 
       - **build** : npm run build
       - **test** : npm run test

## BACK
   - Tehnologie : Nest
   - Actions souhaitées :
       - **dependencies** : npm i 
       - **build** : npm run build
       - **test** : npm run test

**Comment by j-catania** [comment]
C'est très clair :)
Seriez-vous dispo demain pour faire les deux CI ?
