### ISSUE TITLE
Création d'une CI pour le groupe 6

### ISSUE THREAD

**Issue by A-Wakidou** [juu-aix-ynov-campus/documentation#4]
# Prérequis pour la création d'une CI via GitHub Actions

## Front-end
   - Tehnologie : Vue.js
   - Actions souhaitées :
       - install : npm run ci
       - format : npm run format
       - lint : npm run lint
       - build : npm run build
       - test : npm run test

## Mobile
   - Tehnologie : React-native
   - Actions souhaitées :
       - install : npm run ci
       - format : npm run format
       - lint : npm run lint
       - test : npm run test
      
## Back-end
   - Tehnologie : Nest.js
   - Actions souhaitées :
       - install : npm run ci
       - format : npm run format
       - lint : npm run lint
       - build : npm run build
       - test : npm run test

**Comment by j-catania** [comment]
On se fait ça quand tu veux.
On commencera pas le back :)
